### PR TITLE
adding those who contributed to lectures and code

### PR DESCRIPTION
**Pull request by Harveyt47**
Hi @jstac I've added those we co-authored lectures and code in to the [about](https://python.quantecon.org/about/) page on the lecture site.

### CODE REVIEW

**Comment by Harveyt47** [comment]
Just noticed a couple of mistakes hold off on mergin

**Comment by sayaikegawa** [comment]
Thanks @Harveyt47 , It looks nice. 
I found a few things that should be corrected.
1, "Asset Pricing III:   Incomplete Markets" should be changed to "Asset Pricing with Incomplete Markets" 
2, Zejin has also co-authored "Markov Jump Linear   Quadratic Dynamic Programming" (https://python-advanced.quantecon.org/markov_jump_lq.html), so it should be added.
3, "Balint Skoze" should be corrected to "Balint Szoke"
4, The code Balint authored is also used in "Classical Prediction and Filtering With Linear Algebra"(https://python-advanced.quantecon.org/classical_filtering.html)

**Comment by Harveyt47** [comment]
@sayaikegawa thanks! I'll make those changes.

**Comment by sayaikegawa** [comment]
Sorry @Harveyt47 , I found a few things more.
1, Chase and Spencer co-authored Robustness should be "co-authored code for" Robustness
2, Chase's code for "Markov Perfect Equilibrium" is also used in "Robust Markov Perfect Equilibrium"(https://python-advanced.quantecon.org/rob_markov_perf.html)
3, Adding the previous review (1, "Asset Pricing III: Incomplete Markets" should be changed to "Asset Pricing with Incomplete Markets"), Chase co-authored should be "co-authored code for" "Asset Pricing with Incomplete Markets"

**Comment by Harveyt47** [comment]
@sayaikegawa when they Co-author the lecture I think it should be assumed that they also were a part of the writting of the code, no?

**Comment by jstac** [comment]
Please ask @sayaikegawa to look at this again when you are ready, @Harveyt47, and then add the ready label and ping me when @sayaikegawa approves.

**Comment by sayaikegawa** [comment]
Hi @Harveyt47 , Thanks for correcting. 
These are several things can be corrected in your commit (1a61798)

1, adjusting indentation of " Co-authored [Markov Jump Linear Quadratic Dynamic Programming]"

2,  adjusting indentation of "Coauthored code for [Classical Prediction and Filtering With Linear Algebra]"  
And changing "Coauthored' to "Co-authored"

And one thing I mentioned was not added.

1, Chase's code for "Markov Perfect Equilibrium" is also used in "Robust Markov Perfect Equilibrium"(https://python-advanced.quantecon.org/rob_markov_perf.html), so could you add co-authored code for this lecture just under "Markov Perfect Equilibrium".

You might think those two codes are different since one of them has author name but the other doesn't. However, the code in "Robust Markov Perfect Equilibrium" is using the same "duopoly_mpe.py" file as "Markov Perfect Equilibrium". (When I deleted the name first, both of them have author name, but something strange happens now.)

**Comment by sayaikegawa** [comment]
Thanks for correcting @Harveyt47 ,  It looks good for me.

**Comment by Harveyt47** [comment]
Thanks @sayaikegawa for all your help.

**Comment by jstac** [comment]
Thanks @sayaikegawa and @Harveyt47, much appreciated.

**Pull request merged**
